{
 "title": "App / Backend Overview",
 "tags": [
  "portfolio",
  "microservices"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Request rate (req/s)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(app_http_request_duration_seconds_count[5m]))",
     "legendFormat": "req/s"
    }
   ]
  },
  {
   "title": "5xx rate (req/s)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(app_http_request_duration_seconds_count{status_code=~\\\"5..\\\"}[5m]))",
     "legendFormat": "5xx req/s"
    }
   ]
  },
  {
   "title": "Latency p95 (s)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(app_http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Dependencies (1=up)",
   "type": "stat",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    { "expr": "app_dependency_up", "legendFormat": "{{dependency}}" }
   ]
  }
 ]
}