# IRSA example for the backend
#
# WHY:
# - Avoid putting AWS permissions on the node role (too broad)
# - Give pods ONLY the AWS permissions they need (least privilege)
#
# HOW it works:
# - EKS has an OIDC provider associated with the cluster
# - This ServiceAccount gets an annotation pointing to an IAM Role
# - Pods using this SA receive a projected token that AWS STS can exchange
#   for short-lived credentials
#
# You create the IAM role using eksctl (recommended) or Terraform.
# Example (later):
#   eksctl create iamserviceaccount --cluster ${CLUSTER_NAME} --namespace default \
#     --name backend-irsa --attach-policy-arn arn:aws:iam::${AWS_ACCOUNT_ID}:policy/<your-policy> \
#     --approve
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-irsa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/${CLUSTER_NAME}-backend-irsa
