apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-platform-staging
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Raj-glitch-max/FullStack-MicroServices.git
    targetRevision: staging
    path: k8s-manifests/overlays/staging

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
