# Example SealedSecret (placeholder)
#
# Generate your own using kubeseal for your cluster.
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-secret
  namespace: default
spec:
  encryptedData:
    username: REPLACE_WITH_KUBESEAL_OUTPUT
    password: REPLACE_WITH_KUBESEAL_OUTPUT
    database: REPLACE_WITH_KUBESEAL_OUTPUT
  template:
    metadata:
      name: db-secret
      namespace: default
    type: Opaque
