apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-root-prod
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Raj-glitch-max/FullStack-MicroServices.git
    targetRevision: prod
    path: argocd/applications/apps/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
